#!/usr/local/bin/node
console.log('arrays')
let soliloquy = 'To be or not to be, that is the question.'
soliloquyArray = soliloquy.split("e")
console.log(soliloquyArray) 

let a = "A man, a plan, a canal, Panama"
aArray = a.split(",")

console.log(aArray)

let aTest = ""

for(let i = 0; i< aArray.length; i++){
    
    aTest = aTest + (aArray[i].toLowerCase().split("").reverse().join(""))
}
//console.log(aArray.reverse().join())
console.log(aTest)
